### ISSUE TITLE
Error: buildx failed with: ERROR: denied: permission_denied: write_package

### ISSUE THREAD

**Issue by takaishi** [reproio/send-alb-metrics-to-datadog#41]
I tried to release at https://github.com/reproio/send-alb-metrics-to-datadog/actions/runs/7578216166/job/20640443143 , but it failed with following message:

```
------
 > pushing ghcr.io/reproio/send-alb-metrics-to-datadog:latest with docker:
------
ERROR: denied: permission_denied: write_package
Error: buildx failed with: ERROR: denied: permission_denied: write_package
```

I investigated this error I found a reason. We need add permission to write package by package settings in this organization.

For example: https://blog.yukirii.dev/github-action-ghcr-push-error/

**Comment by takaishi** [comment]
@okkez @YAMASHITAHiroki @akihiro17 Could you add permission to write to this repository?

**Comment by takaishi** [comment]
Or, we can discussion to migrate this repository to my account from this org to reduce cost of review or operation.

**Comment by okkez** [comment]
![image](https://github.com/reproio/send-alb-metrics-to-datadog/assets/33111/0ecca5fe-adbf-4b4d-ac57-4e2e9b70d2d9)

**Comment by okkez** [comment]
@takaishi Can you try again?

**Comment by takaishi** [comment]
Pushing image was successfull! But goreleaser didn't push artifacts to release, so I'm going to investigate. Thank you.
